name: driver-driver
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - tqdm
  - pytorch=2.4.0
  - torchvision
  - torchaudio
  - tensorboard
  - jupyterlab
  - ipykernel
  - notebook
  - pyyaml
  - pip:
      - osmnx==1.9.4
      - geopandas==0.13.2
      - shapely==2.0.3
      - plotly==5.20.0
      - folium==0.17.0
      - moviepy==1.0.3
      - streamlit==1.33.0
      - protobuf==4.25.3
      - wordcloud==1.9.3
      - geopy==2.4.1